name: Generate Space Shooter

on:
  schedule:
    - cron: "0 18 * * *" # Runs every night
  workflow_dispatch: # Manual trigger

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Space Shooter SVG
        uses: czl9707/gh-space-shooter@main
        with:
          github_user_name: aimenhamama
          
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generate Space Shooter animation" || echo "No changes to commit"
          git push
